### ISSUE TITLE
Extend "Upload Port" functionality for "Train It!"

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/smartanthill2_0-dashboard#10]
Currently we have one option to upload firmware to "Serial Port". However, @PlatformIO has support for automatic port detection, uploading to media disk(MBED-based boards) and to Serial port.
## GUI

`Device Serial Port` should be renamed to `Upload Port` and should have this GUI:

```
Upload Port: <btn-group, label=btn-default, labels="Auto | Serial Port | Media Drive | Manual"
```

`data.uploadport` should be set with appropriate value in https://github.com/smartanthill/smartanthill2_0-dashboard/blob/develop/app/scripts/controllers/device-trainit.js#L70
### Upload Port = Auto

``` js
data.uploadport = null;
```
### Upload Port = Serial Port

Additional dropdown select should be shown (like in current version)
### Upload Port = Media Drive

Additional dropdown select should be shown with "disks list" from current OS. This info should be taken from Dashboard API (like with Serial Port). Which disks? Use [platformio.util.get_logicaldisks](https://github.com/platformio/platformio/blob/develop/platformio/util.py#L245).
### Upload Port = Manual

Show additional text input with max=100 chars. Any symbols/chars are allowed here.

**Comment by ivankravets** [comment]
@valeros please re-test this issue after closing.

**Comment by dmytrokyrychuk** [comment]
`Train It!` fails when `data.uploadport = null`:

```
2015-08-14 18:37:27+0300 [dashboard.api#error] Unhandled Error
    Traceback (most recent call last):
      ...
    --- <exception caught here> ---
      File "/home/orgkhnargh/code/python/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/orgkhnargh/code/python/smartanthill2_0/smartanthill/dashboard/api.py", line 169, in <lambda>
        d.addCallback(lambda _, data: device.upload_firmware(data),
      File "/home/orgkhnargh/code/python/smartanthill2_0/smartanthill/device/device.py", line 118, in upload_firmware
        data
      File "/home/orgkhnargh/code/python/smartanthill2_0/smartanthill/cc/platformio.py", line 249, in upload_firmware
        return pio.run("upload", {"upload_port": data['uploadport']})
      File "/home/orgkhnargh/code/python/smartanthill2_0/smartanthill/cc/platformio.py", line 77, in run
        return PlatformIOUploader(self, options).run()
      File "/home/orgkhnargh/code/python/smartanthill2_0/smartanthill/cc/platformio.py", line 191, in run
        env=environ
      File "/home/orgkhnargh/code/python/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/utils.py", line 174, in getProcessOutputAndValue
        reactor)
      File "/home/orgkhnargh/code/python/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/utils.py", line 28, in _callProtocolWithDeferred
        reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
      File "/home/orgkhnargh/code/python/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 331, in spawnProcess
        args, env = self._checkProcessArgs(args, env)
      File "/home/orgkhnargh/code/python/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/base.py", line 912, in _checkProcessArgs
        raise TypeError("Arguments contain a non-string value")
    exceptions.TypeError: Arguments contain a non-string value
```

However, firmware upload succeeds when Upload port is set to `Auto` and `data.uploadport = ''`.
